# This is a basic workflow to help you get started with Actions

name: Artifacts

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the "main" branch
 
env:
  ARTIFACTS: myartifacts
jobs:
  main:
   runs-on: ubuntu-latest
   steps: 
    -name: Checkout the code
     uses: actions/checkout@v2
    -name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.ARTIFACTS}}
        path: .
      
  
 


  
 
 
